//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 12:56:55 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.msssi.es/catalogo/base", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.msssi.es.schemas;
